# Model Architecture
model:
  input_size: 784
  hidden_layers: [256, 128, 64] 
  output_size: 10 
  activations: ["relu", "relu", "relu", "softmax"] 
  weight_init: "xavier"
  loss_function: "categorical_crossentropy"
  lambda_l1: 0.0
  lambda_l2: 1e-5

# Training Parameters
training:
  batch_size: 32
  learning_rate: 0.01
  epochs: 10
  verbose: 1

# Weight Initialization Parameters (optional)
weight_init_params:
  lower_bound: -0.1
  upper_bound: 0.1
  seed: 42
  mean: 0
  variance: 0.1

# Data Parameters
data:
  validation_split: 0.2 

# Model Saving
save:
  model_path: "models/saved_model.npy" 
  save_frequency: 10